'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WCM-EXE-SQL01")>  _
        Public ReadOnly Property SQLServer() As String
            Get
                Return CType(Me("SQLServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dairy_sales")>  _
        Public ReadOnly Property Database() As String
            Get
                Return CType(Me("Database"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("P2P")>  _
        Public ReadOnly Property PWD() As String
            Get
                Return CType(Me("PWD"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("P2P")>  _
        Public ReadOnly Property DBUser() As String
            Get
                Return CType(Me("DBUser"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property Email_Success() As String
            Get
                Return CType(Me("Email_Success"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5013546152459")>  _
        Public ReadOnly Property GLN_WCM() As String
            Get
                Return CType(Me("GLN_WCM"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property OrderTo() As String
            Get
                Return CType(Me("OrderTo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property orderfrom() As String
            Get
                Return CType(Me("orderfrom"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property Email_Error() As String
            Get
                Return CType(Me("Email_Error"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5060224840283")>  _
        Public ReadOnly Property GLN_COMPASS() As String
            Get
                Return CType(Me("GLN_COMPASS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100000")>  _
        Public ReadOnly Property TimerInterval() As String
            Get
                Return CType(Me("TimerInterval"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public ReadOnly Property WarningInterval_6to10() As String
            Get
                Return CType(Me("WarningInterval_6to10"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public ReadOnly Property WarningInterval_11to18() As String
            Get
                Return CType(Me("WarningInterval_11to18"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("360")>  _
        Public ReadOnly Property WarningInterval_19to5() As String
            Get
                Return CType(Me("WarningInterval_19to5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("720")>  _
        Public ReadOnly Property WarningInterval_weekend() As String
            Get
                Return CType(Me("WarningInterval_weekend"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Compass() As String
            Get
                Return CType(Me("Switch_Compass"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5055902800000")>  _
        Public ReadOnly Property GLN_CYPAD() As String
            Get
                Return CType(Me("GLN_CYPAD"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Upload\Order")>  _
        Public ReadOnly Property CYPAD_IN() As String
            Get
                Return CType(Me("CYPAD_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Download\Confirmation")>  _
        Public ReadOnly Property CYPAD_OUT() As String
            Get
                Return CType(Me("CYPAD_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Archive")>  _
        Public ReadOnly Property CYPAD_Archive() As String
            Get
                Return CType(Me("CYPAD_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Upload\Falied_Orders")>  _
        Public ReadOnly Property CYPAD_Failed() As String
            Get
                Return CType(Me("CYPAD_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Upload\Order\test")>  _
        Public ReadOnly Property CYPAD_IN_test() As String
            Get
                Return CType(Me("CYPAD_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Download\Confirmation\test")>  _
        Public ReadOnly Property CYPAD_OUT_test() As String
            Get
                Return CType(Me("CYPAD_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Archive")>  _
        Public ReadOnly Property CYPAD_Archive_test() As String
            Get
                Return CType(Me("CYPAD_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Upload\Falied_Orders")>  _
        Public ReadOnly Property CYPAD_Failed_test() As String
            Get
                Return CType(Me("CYPAD_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\P2P_Elior\WAX_ELIOR_PROD\Inbox")>  _
        Public ReadOnly Property ELIOR_IN() As String
            Get
                Return CType(Me("ELIOR_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\P2P_Elior\Upload")>  _
        Public ReadOnly Property ELIOR_OUT() As String
            Get
                Return CType(Me("ELIOR_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Elior_Orders\Failed")>  _
        Public ReadOnly Property ELIOR_Failed() As String
            Get
                Return CType(Me("ELIOR_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Elior_Orders\Processed")>  _
        Public ReadOnly Property ELIOR_Archive() As String
            Get
                Return CType(Me("ELIOR_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\P2P_Elior\WAX_ELIOR_STAGE\Inbox")>  _
        Public ReadOnly Property ELIOR_IN_test() As String
            Get
                Return CType(Me("ELIOR_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\P2P_Elior\Upload_Test")>  _
        Public ReadOnly Property ELIOR_OUT_test() As String
            Get
                Return CType(Me("ELIOR_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Elior_Orders\Failed_test")>  _
        Public ReadOnly Property ELIOR_Failed_test() As String
            Get
                Return CType(Me("ELIOR_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Elior_Orders\Processed_test")>  _
        Public ReadOnly Property ELIOR_Archive_test() As String
            Get
                Return CType(Me("ELIOR_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Live\orders")>  _
        Public ReadOnly Property BOURNE_IN() As String
            Get
                Return CType(Me("BOURNE_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Live\orders\Failed Orders")>  _
        Public ReadOnly Property BOURNE_Failed() As String
            Get
                Return CType(Me("BOURNE_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Live\orders\Processed Orders")>  _
        Public ReadOnly Property BOURNE_Archive() As String
            Get
                Return CType(Me("BOURNE_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Test\orders")>  _
        Public ReadOnly Property BOURNE_IN_test() As String
            Get
                Return CType(Me("BOURNE_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Test\orders\Failed Orders")>  _
        Public ReadOnly Property BOURNE_Failed_test() As String
            Get
                Return CType(Me("BOURNE_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Test\orders\Processed Orders")>  _
        Public ReadOnly Property BOURNE_Archive_test() As String
            Get
                Return CType(Me("BOURNE_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_Medina() As String
            Get
                Return CType(Me("Switch_Medina"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Live\Orders")>  _
        Public ReadOnly Property MEDINA_IN() As String
            Get
                Return CType(Me("MEDINA_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Live\Orders\Failed Orders")>  _
        Public ReadOnly Property MEDINA_Failed() As String
            Get
                Return CType(Me("MEDINA_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Live\Orders\Processed Orders")>  _
        Public ReadOnly Property MEDINA_Archive() As String
            Get
                Return CType(Me("MEDINA_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Test\Orders")>  _
        Public ReadOnly Property MEDINA_IN_test() As String
            Get
                Return CType(Me("MEDINA_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Live\Orders\Failed Orders")>  _
        Public ReadOnly Property MEDINA_Failed_test() As String
            Get
                Return CType(Me("MEDINA_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Live\Orders\Processed Orders")>  _
        Public ReadOnly Property MEDINA_Archive_test() As String
            Get
                Return CType(Me("MEDINA_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_FoodBuyOnline() As String
            Get
                Return CType(Me("Switch_FoodBuyOnline"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS")>  _
        Public ReadOnly Property FoodBuyOnline_IN() As String
            Get
                Return CType(Me("FoodBuyOnline_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Responses")>  _
        Public ReadOnly Property FoodBuyOnline_OUT() As String
            Get
                Return CType(Me("FoodBuyOnline_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Failed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Failed() As String
            Get
                Return CType(Me("FoodBuyOnline_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Processed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Archive() As String
            Get
                Return CType(Me("FoodBuyOnline_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS")>  _
        Public ReadOnly Property FoodBuyOnline_IN_test() As String
            Get
                Return CType(Me("FoodBuyOnline_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Failed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Failed_test() As String
            Get
                Return CType(Me("FoodBuyOnline_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Processed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Archive_test() As String
            Get
                Return CType(Me("FoodBuyOnline_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Live Area")>  _
        Public ReadOnly Property COMPASS_IN() As String
            Get
                Return CType(Me("COMPASS_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Live Area\Responses")>  _
        Public ReadOnly Property COMPASS_OUT() As String
            Get
                Return CType(Me("COMPASS_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Live Area\Aknowlegements")>  _
        Public ReadOnly Property COMPASS_ACKNOWLEDGEMENTS() As String
            Get
                Return CType(Me("COMPASS_ACKNOWLEDGEMENTS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Live Area\Failed_Orders")>  _
        Public ReadOnly Property COMPASS_Failed() As String
            Get
                Return CType(Me("COMPASS_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Live Area\Processed_Orders")>  _
        Public ReadOnly Property COMPASS_Archive() As String
            Get
                Return CType(Me("COMPASS_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Test Area")>  _
        Public ReadOnly Property COMPASS_IN_test() As String
            Get
                Return CType(Me("COMPASS_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Test Area\Responses")>  _
        Public ReadOnly Property COMPASS_OUT_test() As String
            Get
                Return CType(Me("COMPASS_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Test Area\Failed")>  _
        Public ReadOnly Property COMPASS_Failed_test() As String
            Get
                Return CType(Me("COMPASS_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Test Area\Processed")>  _
        Public ReadOnly Property COMPASS_Archive_test() As String
            Get
                Return CType(Me("COMPASS_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\P2P_Elior\Upload\Processed_Responses")>  _
        Public ReadOnly Property ELIOR_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("ELIOR_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\P2P_Elior\Upload_Test\Processed_Responses")>  _
        Public ReadOnly Property ELIOR_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("ELIOR_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\ELIOR_Waterfall\ORDERS\Responses\Processed")>  _
        Public ReadOnly Property Waterfall_Response_archived() As String
            Get
                Return CType(Me("Waterfall_Response_archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\ELIOR_Waterfall\ORDERS\Responses\Processed")>  _
        Public ReadOnly Property Waterfall_response_archived_test() As String
            Get
                Return CType(Me("Waterfall_response_archived_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\ELIOR_Waterfall\ORDERS\Responses")>  _
        Public ReadOnly Property Waterfall_OUT_test() As String
            Get
                Return CType(Me("Waterfall_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property MEDINA_OUT() As String
            Get
                Return CType(Me("MEDINA_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property MEDINA_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("MEDINA_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property MEDINA_OUT_test() As String
            Get
                Return CType(Me("MEDINA_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property MEDINA_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("MEDINA_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Live Area\Aknowlegements\Processed")>  _
        Public ReadOnly Property COMPASS_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("COMPASS_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Test Area\Aknowlegements")>  _
        Public ReadOnly Property COMPASS_ACKNOWLEDGEMENTS_test() As String
            Get
                Return CType(Me("COMPASS_ACKNOWLEDGEMENTS_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Compass FTP Test Area\Aknowlegements\Processed")>  _
        Public ReadOnly Property COMPASS_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("COMPASS_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Download\Confirmation\Processed")>  _
        Public ReadOnly Property CYPAD_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("CYPAD_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Cypad_Orders\Download\Confirmation\Processed")>  _
        Public ReadOnly Property CYPAD_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("CYPAD_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("BOURNE_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("BOURNE_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_OUT() As String
            Get
                Return CType(Me("BOURNE_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_OUT_test() As String
            Get
                Return CType(Me("BOURNE_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders\Orders")>  _
        Public ReadOnly Property EmailOrders_IN() As String
            Get
                Return CType(Me("EmailOrders_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders\Orders\Processed")>  _
        Public ReadOnly Property EmailOrders_Archive() As String
            Get
                Return CType(Me("EmailOrders_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders\Orders\Failed")>  _
        Public ReadOnly Property EmailOrders_Failed() As String
            Get
                Return CType(Me("EmailOrders_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders\Acknowledgments")>  _
        Public ReadOnly Property EmailOrders_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("EmailOrders_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders_TEST\Orders")>  _
        Public ReadOnly Property EmailOrders_IN_test() As String
            Get
                Return CType(Me("EmailOrders_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders_TEST\Orders\Processed")>  _
        Public ReadOnly Property EmailOrders_Archive_test() As String
            Get
                Return CType(Me("EmailOrders_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders_TEST\Orders\Failed")>  _
        Public ReadOnly Property EmailOrders_Failed_test() As String
            Get
                Return CType(Me("EmailOrders_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_Email_orders_TEST\Acknowledgments")>  _
        Public ReadOnly Property EmailOrders_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("EmailOrders_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_DN\Grahams")>  _
        Public ReadOnly Property DN_Grahams_IN() As String
            Get
                Return CType(Me("DN_Grahams_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_DN\Grahams\Processed")>  _
        Public ReadOnly Property DN_Grahams_Archive() As String
            Get
                Return CType(Me("DN_Grahams_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_DN\Grahams\Failed")>  _
        Public ReadOnly Property DN_Grahams_Failed() As String
            Get
                Return CType(Me("DN_Grahams_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\")>  _
        Public ReadOnly Property POUNDLAND_IN() As String
            Get
                Return CType(Me("POUNDLAND_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\OUTBOX")>  _
        Public ReadOnly Property POUNDLAND_OUT() As String
            Get
                Return CType(Me("POUNDLAND_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\INBOX\Failed")>  _
        Public ReadOnly Property POUNDLAND_Failed() As String
            Get
                Return CType(Me("POUNDLAND_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\INBOX\Processed")>  _
        Public ReadOnly Property POUNDLAND_Archive() As String
            Get
                Return CType(Me("POUNDLAND_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND_test\INBOX")>  _
        Public ReadOnly Property POUNDLAND_IN_test() As String
            Get
                Return CType(Me("POUNDLAND_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND_test\OUTBOX")>  _
        Public ReadOnly Property POUNDLAND_OUT_test() As String
            Get
                Return CType(Me("POUNDLAND_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\INBOX\Failed")>  _
        Public ReadOnly Property POUNDLAND_Failed_test() As String
            Get
                Return CType(Me("POUNDLAND_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\INBOX\Processed")>  _
        Public ReadOnly Property POUNDLAND_Archived_test() As String
            Get
                Return CType(Me("POUNDLAND_Archived_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\OUTBOX\Processed")>  _
        Public ReadOnly Property POUNDLAND_RESPONSE_Archived() As String
            Get
                Return CType(Me("POUNDLAND_RESPONSE_Archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\POUNDLAND\OUTBOX\Processed")>  _
        Public ReadOnly Property POUNDLAND_RESPONSE_Archived_test() As String
            Get
                Return CType(Me("POUNDLAND_RESPONSE_Archived_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Cypad() As Integer
            Get
                Return CType(Me("Switch_Cypad"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_Elior() As Integer
            Get
                Return CType(Me("Switch_Elior"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Bourne() As Integer
            Get
                Return CType(Me("Switch_Bourne"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_EmailOrders() As Integer
            Get
                Return CType(Me("Switch_EmailOrders"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_DN_Grahams() As Integer
            Get
                Return CType(Me("Switch_DN_Grahams"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Poundland() As Integer
            Get
                Return CType(Me("Switch_Poundland"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_DairyData_JN() As Integer
            Get
                Return CType(Me("Switch_DairyData_JN"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\JNDairies\out")>  _
        Public ReadOnly Property DairyData_JN_OUT() As String
            Get
                Return CType(Me("DairyData_JN_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_DairyData_FP() As Integer
            Get
                Return CType(Me("Switch_DairyData_FP"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\FreshPastures\out")>  _
        Public ReadOnly Property DairyData_FP_OUT() As String
            Get
                Return CType(Me("DairyData_FP_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\FreshPastures\processed")>  _
        Public ReadOnly Property DairyData_FP_OUT_ARCHIVE() As String
            Get
                Return CType(Me("DairyData_FP_OUT_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_DairyData_DHT() As Integer
            Get
                Return CType(Me("Switch_DairyData_DHT"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\DHT\out")>  _
        Public ReadOnly Property DairyData_DHT_OUT() As String
            Get
                Return CType(Me("DairyData_DHT_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\DHT\processed")>  _
        Public ReadOnly Property DairyData_DHT_ARCHIVE() As String
            Get
                Return CType(Me("DairyData_DHT_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_AllanReeder() As Integer
            Get
                Return CType(Me("Switch_AllanReeder"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\AllanReeder_Orders")>  _
        Public ReadOnly Property AllanReeder_OUT() As String
            Get
                Return CType(Me("AllanReeder_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\AllanReeder_Orders\Archive")>  _
        Public ReadOnly Property AllanReeder_ARCHIVE() As String
            Get
                Return CType(Me("AllanReeder_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_Medina_TC9() As Integer
            Get
                Return CType(Me("Switch_Medina_TC9"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_orderfile\Automated")>  _
        Public ReadOnly Property MEDINA_TC9_OUT() As String
            Get
                Return CType(Me("MEDINA_TC9_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("129624393")>  _
        Public ReadOnly Property MEDINA_TC9_SUPPL_ID() As Long
            Get
                Return CType(Me("MEDINA_TC9_SUPPL_ID"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1994679")>  _
        Public ReadOnly Property DairyData_JN_SUPPL_ID() As Long
            Get
                Return CType(Me("DairyData_JN_SUPPL_ID"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("137448846")>  _
        Public ReadOnly Property DairyData_DHT_SUPPL_ID() As Long
            Get
                Return CType(Me("DairyData_DHT_SUPPL_ID"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("195275002")>  _
        Public ReadOnly Property DairyData_FP_SUPPL_ID() As Long
            Get
                Return CType(Me("DairyData_FP_SUPPL_ID"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127695324")>  _
        Public ReadOnly Property AllanReeder_SUPPL_ID() As Long
            Get
                Return CType(Me("AllanReeder_SUPPL_ID"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\JNDairies\processed")>  _
        Public ReadOnly Property DairyData_JN_ARCHIVE() As String
            Get
                Return CType(Me("DairyData_JN_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Paynes_Orders")>  _
        Public ReadOnly Property Paynes_OUT() As String
            Get
                Return CType(Me("Paynes_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("240305512")>  _
        Public ReadOnly Property Paynes_SUPPL_ID() As Long
            Get
                Return CType(Me("Paynes_SUPPL_ID"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Processed")>  _
        Public ReadOnly Property CN_CrunchTime_Archived_Test() As String
            Get
                Return CType(Me("CN_CrunchTime_Archived_Test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test")>  _
        Public ReadOnly Property CN_CrunchTime_IN_test() As String
            Get
                Return CType(Me("CN_CrunchTime_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Failed")>  _
        Public ReadOnly Property CN_CrunchTime_Failed_test() As String
            Get
                Return CType(Me("CN_CrunchTime_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Response")>  _
        Public ReadOnly Property CN_CrunchTime_OUT_test() As String
            Get
                Return CType(Me("CN_CrunchTime_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Response_Archive")>  _
        Public ReadOnly Property CN_CrunchTime_RESPONSE_Archived_test() As String
            Get
                Return CType(Me("CN_CrunchTime_RESPONSE_Archived_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero")>  _
        Public ReadOnly Property CN_CrunchTime_IN() As String
            Get
                Return CType(Me("CN_CrunchTime_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Processed")>  _
        Public ReadOnly Property CN_CrunchTime_Archive() As String
            Get
                Return CType(Me("CN_CrunchTime_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Failed")>  _
        Public ReadOnly Property CN_CrunchTime_Failed() As String
            Get
                Return CType(Me("CN_CrunchTime_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Response")>  _
        Public ReadOnly Property CN_CrunchTime_OUT() As String
            Get
                Return CType(Me("CN_CrunchTime_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Response_Archive")>  _
        Public ReadOnly Property CN_CrunchTime_RESPONSE_Archived() As String
            Get
                Return CType(Me("CN_CrunchTime_RESPONSE_Archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HeidiReeder@allanreederltd.co.uk;frances@allanreederltd.co.uk;Info@allanreederltd"& _ 
            ".co.uk")>  _
        Public ReadOnly Property AllanReeder_Summary_Email() As String
            Get
                Return CType(Me("AllanReeder_Summary_Email"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property Switch_CN_CrunchTime() As Integer
            Get
                Return CType(Me("Switch_CN_CrunchTime"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property Switch_ZUPA() As Integer
            Get
                Return CType(Me("Switch_ZUPA"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet\ORDER_IN")>  _
        Public ReadOnly Property ZUPA_IN() As String
            Get
                Return CType(Me("ZUPA_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet\INVOICE_OUT\ORDER_RESPONSE")>  _
        Public ReadOnly Property ZUPA_OUT() As String
            Get
                Return CType(Me("ZUPA_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet\ORDER_Failed")>  _
        Public ReadOnly Property ZUPA_Failed() As String
            Get
                Return CType(Me("ZUPA_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet\ORDER_Processed")>  _
        Public ReadOnly Property ZUPA_Archive() As String
            Get
                Return CType(Me("ZUPA_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet_Test\ORDER_IN")>  _
        Public ReadOnly Property ZUPA_IN_test() As String
            Get
                Return CType(Me("ZUPA_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet_Test\INVOICE_OUT\ORDER_RESPONSE")>  _
        Public ReadOnly Property ZUPA_OUT_test() As String
            Get
                Return CType(Me("ZUPA_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet_test\ORDER_Failed")>  _
        Public ReadOnly Property ZUPA_Failed_test() As String
            Get
                Return CType(Me("ZUPA_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet_test\ORDER_IN\ORDER_Processed")>  _
        Public ReadOnly Property ZUPA_Archive_test() As String
            Get
                Return CType(Me("ZUPA_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet\ORDER_RESPONSE_ARCHIVED")>  _
        Public ReadOnly Property ZUPA_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("ZUPA_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Zupa_Caternet_test\ORDER_RESPONSE_ARCHIVED")>  _
        Public ReadOnly Property ZUPA_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("ZUPA_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Johal() As Integer
            Get
                Return CType(Me("Switch_Johal"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Johal_Orders")>  _
        Public ReadOnly Property Johal_OUT() As String
            Get
                Return CType(Me("Johal_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Johal_Orders\Archive")>  _
        Public ReadOnly Property Johal_ARCHIVE() As String
            Get
                Return CType(Me("Johal_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1188")>  _
        Public ReadOnly Property Johal_SUPPL_ID() As String
            Get
                Return CType(Me("Johal_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_PushEmailP2P() As Integer
            Get
                Return CType(Me("Switch_PushEmailP2P"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_PushEmailWebApp() As Integer
            Get
                Return CType(Me("Switch_PushEmailWebApp"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5060642190021")>  _
        Public ReadOnly Property GLN_INTERSERVE() As String
            Get
                Return CType(Me("GLN_INTERSERVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_IN_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_IN_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_SAFFRON\Failed")>  _
        Public ReadOnly Property INTERSERVE_Failed_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Failed_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_Archive_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Archive_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_TEST_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_IN_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_IN_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_TEST_SAFFRON\Failed")>  _
        Public ReadOnly Property INTERSERVE_Failed_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Failed_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_TEST_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_Archive_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Archive_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_OUT_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_OUT_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_RESPONSE_ARCHIVED_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_RESPONSE_ARCHIVED_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_Test_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_OUT_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_OUT_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_Test_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_RESPONSE_ARCHIVED_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_RESPONSE_ARCHIVED_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property Switch_Interserve_Saffron() As String
            Get
                Return CType(Me("Switch_Interserve_Saffron"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_McColls() As Integer
            Get
                Return CType(Me("Switch_McColls"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\McColls\ORDER_IN")>  _
        Public ReadOnly Property MCCOLLS_IN() As String
            Get
                Return CType(Me("MCCOLLS_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\McColls\ORDER_IN\Processed")>  _
        Public ReadOnly Property MCCOLLS_Archive() As String
            Get
                Return CType(Me("MCCOLLS_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\McColls\ORDER_IN\Failed")>  _
        Public ReadOnly Property MCCOLLS_Failed() As String
            Get
                Return CType(Me("MCCOLLS_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property MCCOLLS_OUT() As String
            Get
                Return CType(Me("MCCOLLS_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property MCCOLLS_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("MCCOLLS_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@mccolls.co.uk                         ")>  _
        Public ReadOnly Property MCCOLLS_RESPONSE_EMAIL() As String
            Get
                Return CType(Me("MCCOLLS_RESPONSE_EMAIL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CSkellern@mccolls.co.uk")>  _
        Public ReadOnly Property MCCOLLS_RESPONSE_EMAIL_test() As String
            Get
                Return CType(Me("MCCOLLS_RESPONSE_EMAIL_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Weezy() As String
            Get
                Return CType(Me("Switch_Weezy"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WeezyOrders\Processed")>  _
        Public ReadOnly Property WEEZY_Archive() As String
            Get
                Return CType(Me("WEEZY_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WeezyOrders\Failed")>  _
        Public ReadOnly Property WEEZY_Failed() As String
            Get
                Return CType(Me("WEEZY_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property WEEZY_OUT() As String
            Get
                Return CType(Me("WEEZY_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WeezyOrders")>  _
        Public ReadOnly Property WEEZY_IN() As String
            Get
                Return CType(Me("WEEZY_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("118867089")>  _
        Public ReadOnly Property Broadland_SUPPL_ID() As String
            Get
                Return CType(Me("Broadland_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Broadland_Orders")>  _
        Public ReadOnly Property Broadland_OUT() As String
            Get
                Return CType(Me("Broadland_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Broadland() As Integer
            Get
                Return CType(Me("Switch_Broadland"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Paynes() As Integer
            Get
                Return CType(Me("Switch_Paynes"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Paynes_Orders\Archive")>  _
        Public ReadOnly Property Paynes_Archived() As String
            Get
                Return CType(Me("Paynes_Archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_Chew_Valley() As Integer
            Get
                Return CType(Me("Switch_Chew_Valley"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Chew_valley_Orders")>  _
        Public ReadOnly Property Chew_Valley_OUT() As String
            Get
                Return CType(Me("Chew_Valley_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("224513559")>  _
        Public ReadOnly Property Chew_Valley_SUPPL_ID() As Decimal
            Get
                Return CType(Me("Chew_Valley_SUPPL_ID"),Decimal)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property Switch_JJWilson() As Integer
            Get
                Return CType(Me("Switch_JJWilson"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\JJWilson_Orders")>  _
        Public ReadOnly Property JJWilson_Orders() As String
            Get
                Return CType(Me("JJWilson_Orders"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\JJWilson_Orders\Archived")>  _
        Public ReadOnly Property JJWilson_Archived() As String
            Get
                Return CType(Me("JJWilson_Archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("service@jjwilsonltd.com")>  _
        Public ReadOnly Property JJWilson_Email() As String
            Get
                Return CType(Me("JJWilson_Email"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property Switch_DairyData_Medina() As Integer
            Get
                Return CType(Me("Switch_DairyData_Medina"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Live\Orders Out")>  _
        Public ReadOnly Property DairyData_Medina_OUT() As String
            Get
                Return CType(Me("DairyData_Medina_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("227428838")>  _
        Public ReadOnly Property DairyData_Medina_SUPPL_ID() As Decimal
            Get
                Return CType(Me("DairyData_Medina_SUPPL_ID"),Decimal)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Medina  Test\Orders Out")>  _
        Public ReadOnly Property DairyData_Medina_OUT_test() As String
            Get
                Return CType(Me("DairyData_Medina_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Grahamsdairies\Live\ORDERS")>  _
        Public ReadOnly Property Grahams_OUT() As String
            Get
                Return CType(Me("Grahams_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Grahamsdairies\Live\ORDERS\Processed")>  _
        Public ReadOnly Property Grahams_ARCHIVE() As String
            Get
                Return CType(Me("Grahams_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1158")>  _
        Public ReadOnly Property Grahams_SUPPL_ID() As Decimal
            Get
                Return CType(Me("Grahams_SUPPL_ID"),Decimal)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Grahams() As Integer
            Get
                Return CType(Me("Switch_Grahams"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Switch_DairyData_MillsMilk() As Integer
            Get
                Return CType(Me("Switch_DairyData_MillsMilk"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("226047140")>  _
        Public ReadOnly Property MillsMilk_SUPPL_ID() As Decimal
            Get
                Return CType(Me("MillsMilk_SUPPL_ID"),Decimal)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\MillsMilk")>  _
        Public ReadOnly Property DairyData_MillsMilk_OUT() As String
            Get
                Return CType(Me("DairyData_MillsMilk_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\MillsMilk\Archive")>  _
        Public ReadOnly Property DairyData_MillsMilk_Archive() As String
            Get
                Return CType(Me("DairyData_MillsMilk_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("edi@johaldairies.co.uk")>  _
        Public ReadOnly Property Johal_Order_Email() As String
            Get
                Return CType(Me("Johal_Order_Email"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WCMOrdering.My.MySettings
            Get
                Return Global.WCMOrdering.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
