'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WCM-SQL01")>  _
        Public ReadOnly Property SQLServer() As String
            Get
                Return CType(Me("SQLServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dairy_sales")>  _
        Public ReadOnly Property Database() As String
            Get
                Return CType(Me("Database"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N3xu505WcM!")>  _
        Public ReadOnly Property PWD() As String
            Get
                Return CType(Me("PWD"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sa")>  _
        Public ReadOnly Property DBUser() As String
            Get
                Return CType(Me("DBUser"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property Email_Success() As String
            Get
                Return CType(Me("Email_Success"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5013546152459")>  _
        Public ReadOnly Property GLN_WCM() As String
            Get
                Return CType(Me("GLN_WCM"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property OrderTo() As String
            Get
                Return CType(Me("OrderTo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property orderfrom() As String
            Get
                Return CType(Me("orderfrom"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("orders@wcmilk.co.uk")>  _
        Public ReadOnly Property Email_Error() As String
            Get
                Return CType(Me("Email_Error"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100000")>  _
        Public ReadOnly Property TimerInterval() As String
            Get
                Return CType(Me("TimerInterval"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public ReadOnly Property WarningInterval_6to10() As String
            Get
                Return CType(Me("WarningInterval_6to10"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public ReadOnly Property WarningInterval_11to18() As String
            Get
                Return CType(Me("WarningInterval_11to18"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("360")>  _
        Public ReadOnly Property WarningInterval_19to5() As String
            Get
                Return CType(Me("WarningInterval_19to5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("720")>  _
        Public ReadOnly Property WarningInterval_weekend() As String
            Get
                Return CType(Me("WarningInterval_weekend"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Bourne() As String
            Get
                Return CType(Me("Switch_Bourne"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Live\orders")>  _
        Public ReadOnly Property BOURNE_IN() As String
            Get
                Return CType(Me("BOURNE_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Live\orders\Failed Orders")>  _
        Public ReadOnly Property BOURNE_Failed() As String
            Get
                Return CType(Me("BOURNE_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Live\orders\Processed Orders")>  _
        Public ReadOnly Property BOURNE_Archive() As String
            Get
                Return CType(Me("BOURNE_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Test\orders")>  _
        Public ReadOnly Property BOURNE_IN_test() As String
            Get
                Return CType(Me("BOURNE_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Test\orders\Failed Orders")>  _
        Public ReadOnly Property BOURNE_Failed_test() As String
            Get
                Return CType(Me("BOURNE_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Bourne Leisure Test\orders\Processed Orders")>  _
        Public ReadOnly Property BOURNE_Archive_test() As String
            Get
                Return CType(Me("BOURNE_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_CN_CrunchTime() As String
            Get
                Return CType(Me("Switch_CN_CrunchTime"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Processed")>  _
        Public ReadOnly Property CN_CrunchTime_Archived_Test() As String
            Get
                Return CType(Me("CN_CrunchTime_Archived_Test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test")>  _
        Public ReadOnly Property CN_CrunchTime_IN_test() As String
            Get
                Return CType(Me("CN_CrunchTime_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Failed")>  _
        Public ReadOnly Property CN_CrunchTime_Failed_test() As String
            Get
                Return CType(Me("CN_CrunchTime_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Response")>  _
        Public ReadOnly Property CN_CrunchTime_OUT_test() As String
            Get
                Return CType(Me("CN_CrunchTime_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Test\Response_Archive")>  _
        Public ReadOnly Property CN_CrunchTime_RESPONSE_Archived_test() As String
            Get
                Return CType(Me("CN_CrunchTime_RESPONSE_Archived_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero")>  _
        Public ReadOnly Property CN_CrunchTime_IN() As String
            Get
                Return CType(Me("CN_CrunchTime_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Processed")>  _
        Public ReadOnly Property CN_CrunchTime_Archive() As String
            Get
                Return CType(Me("CN_CrunchTime_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Failed")>  _
        Public ReadOnly Property CN_CrunchTime_Failed() As String
            Get
                Return CType(Me("CN_CrunchTime_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Response")>  _
        Public ReadOnly Property CN_CrunchTime_OUT() As String
            Get
                Return CType(Me("CN_CrunchTime_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Crunchtime!\CaffeNero\Response_Archive")>  _
        Public ReadOnly Property CN_CrunchTime_RESPONSE_Archived() As String
            Get
                Return CType(Me("CN_CrunchTime_RESPONSE_Archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_FoodBuyOnline() As String
            Get
                Return CType(Me("Switch_FoodBuyOnline"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS")>  _
        Public ReadOnly Property FoodBuyOnline_IN() As String
            Get
                Return CType(Me("FoodBuyOnline_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Responses")>  _
        Public ReadOnly Property FoodBuyOnline_OUT() As String
            Get
                Return CType(Me("FoodBuyOnline_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Failed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Failed() As String
            Get
                Return CType(Me("FoodBuyOnline_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Processed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Archive() As String
            Get
                Return CType(Me("FoodBuyOnline_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS")>  _
        Public ReadOnly Property FoodBuyOnline_IN_test() As String
            Get
                Return CType(Me("FoodBuyOnline_IN_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Failed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Failed_test() As String
            Get
                Return CType(Me("FoodBuyOnline_Failed_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\FoodBuy_Online\ORDERS\Processed_Orders")>  _
        Public ReadOnly Property FoodBuyOnline_Archive_test() As String
            Get
                Return CType(Me("FoodBuyOnline_Archive_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Interserve_Saffron() As String
            Get
                Return CType(Me("Switch_Interserve_Saffron"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5060642190021")>  _
        Public ReadOnly Property GLN_INTERSERVE() As String
            Get
                Return CType(Me("GLN_INTERSERVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_IN_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_IN_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_SAFFRON\Failed")>  _
        Public ReadOnly Property INTERSERVE_Failed_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Failed_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_Archive_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Archive_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_TEST_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_IN_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_IN_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_TEST_SAFFRON\Failed")>  _
        Public ReadOnly Property INTERSERVE_Failed_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Failed_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ORDER_IN_TEST_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_Archive_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_Archive_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_OUT_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_OUT_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_RESPONSE_ARCHIVED_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_RESPONSE_ARCHIVED_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_Test_SAFFRON")>  _
        Public ReadOnly Property INTERSERVE_OUT_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_OUT_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\INTERSERVE\ASN_Test_SAFFRON\Processed")>  _
        Public ReadOnly Property INTERSERVE_RESPONSE_ARCHIVED_test_SAFFRON() As String
            Get
                Return CType(Me("INTERSERVE_RESPONSE_ARCHIVED_test_SAFFRON"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Grahams() As String
            Get
                Return CType(Me("Switch_Grahams"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1158")>  _
        Public ReadOnly Property Grahams_SUPPL_ID() As String
            Get
                Return CType(Me("Grahams_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Grahamsdairies\Live\ORDERS")>  _
        Public ReadOnly Property Grahams_OUT() As String
            Get
                Return CType(Me("Grahams_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Grahamsdairies\Live\ORDERS\Processed")>  _
        Public ReadOnly Property Grahams_ARCHIVE() As String
            Get
                Return CType(Me("Grahams_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_DN_Grahams() As String
            Get
                Return CType(Me("Switch_DN_Grahams"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_DN\Grahams")>  _
        Public ReadOnly Property DN_Grahams_IN() As String
            Get
                Return CType(Me("DN_Grahams_IN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_DN\Grahams\Processed")>  _
        Public ReadOnly Property DN_Grahams_Archive() As String
            Get
                Return CType(Me("DN_Grahams_Archive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\WCM_DN\Grahams\Failed")>  _
        Public ReadOnly Property DN_Grahams_Failed() As String
            Get
                Return CType(Me("DN_Grahams_Failed"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_JJWilson() As String
            Get
                Return CType(Me("Switch_JJWilson"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\JJWilson_Orders")>  _
        Public ReadOnly Property JJWilson_Orders() As String
            Get
                Return CType(Me("JJWilson_Orders"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\JJWilson_Orders\Archived")>  _
        Public ReadOnly Property JJWilson_Archived() As String
            Get
                Return CType(Me("JJWilson_Archived"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("service@jjwilsonltd.com")>  _
        Public ReadOnly Property JJWilson_Email() As String
            Get
                Return CType(Me("JJWilson_Email"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_DairyData_MillsMilk() As String
            Get
                Return CType(Me("Switch_DairyData_MillsMilk"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("226047140")>  _
        Public ReadOnly Property MillsMilk_SUPPL_ID() As String
            Get
                Return CType(Me("MillsMilk_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\MillsMilk")>  _
        Public ReadOnly Property DairyData_MillsMilk_OUT() As String
            Get
                Return CType(Me("DairyData_MillsMilk_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\DairyData\MillsMilk\Archive")>  _
        Public ReadOnly Property DairyData_MillsMilk_ARCHIVE() As String
            Get
                Return CType(Me("DairyData_MillsMilk_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_AllanReeder() As String
            Get
                Return CType(Me("Switch_AllanReeder"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\AllanReeder_Orders")>  _
        Public ReadOnly Property AllanReeder_OUT() As String
            Get
                Return CType(Me("AllanReeder_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\AllanReeder_Orders\Archive")>  _
        Public ReadOnly Property AllanReeder_ARCHIVE() As String
            Get
                Return CType(Me("AllanReeder_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Paynes() As String
            Get
                Return CType(Me("Switch_Paynes"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("240305512")>  _
        Public ReadOnly Property Paynes_SUPPL_ID() As String
            Get
                Return CType(Me("Paynes_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Paynes_Orders")>  _
        Public ReadOnly Property Paynes_OUT() As String
            Get
                Return CType(Me("Paynes_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Johal() As String
            Get
                Return CType(Me("Switch_Johal"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1188")>  _
        Public ReadOnly Property Johal_SUPPL_ID() As String
            Get
                Return CType(Me("Johal_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Johal_Orders")>  _
        Public ReadOnly Property Johal_OUT() As String
            Get
                Return CType(Me("Johal_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Johal_Orders\Archive")>  _
        Public ReadOnly Property Johal_ARCHIVE() As String
            Get
                Return CType(Me("Johal_ARCHIVE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_PushEmailP2P() As String
            Get
                Return CType(Me("Switch_PushEmailP2P"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_PushEmailWebApp() As String
            Get
                Return CType(Me("Switch_PushEmailWebApp"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property Switch_Broadland() As String
            Get
                Return CType(Me("Switch_Broadland"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("118867089")>  _
        Public ReadOnly Property Broadland_SUPPL_ID() As String
            Get
                Return CType(Me("Broadland_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Broadland_Orders")>  _
        Public ReadOnly Property Broadland_OUT() As String
            Get
                Return CType(Me("Broadland_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HeidiReeder@allanreederltd.co.uk;frances@allanreederltd.co.uk;Info@allanreederltd"& _ 
            ".co.uk")>  _
        Public ReadOnly Property AllanReeder_Summary_Email() As String
            Get
                Return CType(Me("AllanReeder_Summary_Email"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_RESPONSE_ARCHIVED() As String
            Get
                Return CType(Me("BOURNE_RESPONSE_ARCHIVED"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_RESPONSE_ARCHIVED_test() As String
            Get
                Return CType(Me("BOURNE_RESPONSE_ARCHIVED_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_OUT() As String
            Get
                Return CType(Me("BOURNE_OUT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property BOURNE_OUT_test() As String
            Get
                Return CType(Me("BOURNE_OUT_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("edi@johaldairies.co.uk")>  _
        Public ReadOnly Property Johal_Order_Email() As String
            Get
                Return CType(Me("Johal_Order_Email"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127695324")>  _
        Public ReadOnly Property AllanReeder_SUPPL_ID() As String
            Get
                Return CType(Me("AllanReeder_SUPPL_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\WCM-EXE-FP01\Officeshare\Paynes_Orders\Archive")>  _
        Public ReadOnly Property Paynes_Archived() As String
            Get
                Return CType(Me("Paynes_Archived"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WCMOrdering.My.MySettings
            Get
                Return Global.WCMOrdering.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
